# Generated by Django 3.2.9 on 2021-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsdata',
            name='tool_upload_file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
