# Generated by Django 3.2.9 on 2021-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0003_toolsdata_tool_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsdata',
            name='tool_upload_support_document',
            field=models.FileField(default=None, upload_to='supportDocument/'),
        ),
    ]
