# Generated by Django 3.2.9 on 2021-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0005_alter_toolsdata_tool_upload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsdata',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tools Data'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('ANDROID', 'Android'), ('DEVELOPER', 'Developer'), ('TRANSLATOR', 'Translator')], max_length=50),
        ),
    ]
