# Generated by Django 3.2.9 on 2022-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0006_auto_20211217_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_heading_name', models.CharField(max_length=100)),
                ('resource_discription', models.CharField(max_length=5000)),
                ('resource_category', models.CharField(choices=[('Citizen', 'Citizen'), ('Developer', 'Developer'), ('Android', 'Android'), ('Translator', 'Translator')], default='', max_length=50)),
                ('resource_image', models.ImageField(upload_to='images/resources')),
                ('resource_version_number', models.CharField(max_length=10)),
                ('resource_file_size', models.CharField(max_length=30)),
                ('resource_support_document_link', models.CharField(max_length=200)),
                ('resource_upload_support_document', models.FileField(default=None, upload_to='supportDocument/')),
                ('resource_upload_file', models.FileField(default=None, upload_to='Others/static/others/resource/')),
                ('resource_download_link', models.CharField(max_length=200)),
                ('resource_uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('resource_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('resource_download_counter', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Resources Data',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Android', 'Android'), ('Developer', 'Developer'), ('Translator', 'Translator')], max_length=50),
        ),
    ]
