# Generated by Django 3.2.9 on 2022-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0007_auto_20220324_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesdata',
            name='resource_category',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Developer', 'Developer'), ('Android', 'Android'), ('Translator', 'Translator'), ('Training', 'Training')], default='', max_length=50),
        ),
    ]
