# Generated by Django 3.2.9 on 2022-03-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0008_alter_resourcesdata_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Android', 'Android'), ('Developer', 'Developer'), ('Translator', 'Translator'), ('Training', 'Training')], max_length=50),
        ),
    ]
