# Generated by Django 3.2.9 on 2022-03-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0009_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStoriesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_stories_category_name', models.CharField(choices=[('Startup Deployment', 'Startup Deployment'), ('Localisation Deployment', 'Localisation Deployment'), ('Proof of concept/Demo', 'Proof of concept/Demo'), ('Services Deployment', 'Services Deployment'), ('AP Success Stories', 'AP Success Stories'), ('Advanced Features', 'Advanced Features'), ('Archive', 'Archive')], max_length=50)),
                ('success_stories_category_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'SuccessStoriesCategory',
            },
        ),
    ]
