# Generated by Django 3.2.9 on 2022-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0010_successstoriescategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_stories_heading_name', models.CharField(max_length=100)),
                ('success_stories_discription', models.TextField(max_length=10000)),
                ('success_stories_images', models.ImageField(upload_to='Others/static/others/success_stories/images/')),
                ('success_stories_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('success_stories_last_updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('success_stories_published_status', models.BooleanField(default='')),
                ('success_stories_published_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'SuccessStories',
            },
        ),
    ]
