# Generated by Django 3.2.9 on 2022-03-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0011_successstories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessStories',
        ),
    ]
