# Generated by Django 3.2.9 on 2022-03-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0013_successstories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstoriescategory',
            options={'ordering': ['success_stories_category_name'], 'verbose_name_plural': 'SuccessStoriesCategory'},
        ),
    ]
