# Generated by Django 3.2.9 on 2022-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0014_alter_successstoriescategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstories',
            name='success_stories_images',
            field=models.ImageField(upload_to='others/success_stories/images/'),
        ),
    ]
