# Generated by Django 3.2.9 on 2022-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0015_alter_successstories_success_stories_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstories',
            name='success_stories_images',
            field=models.ImageField(upload_to='static/others/success_stories/images/'),
        ),
    ]
