# Generated by Django 3.2.9 on 2022-03-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0016_alter_successstories_success_stories_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstories',
            name='success_stories_images',
            field=models.ImageField(upload_to='Others/static/others/success_stories_images/'),
        ),
    ]
