# Generated by Django 3.2.9 on 2022-04-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0019_successstories_success_stories_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_events_detail', models.CharField(max_length=100)),
                ('news_events_link', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'NewsEvents',
            },
        ),
    ]
