# Generated by Django 3.2.9 on 2022-04-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Others', '0020_newsevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogs_images',
            field=models.ImageField(upload_to='Others/static/others/blogs/'),
        ),
    ]
